// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import ThemeRegistry from "@/theme/themeRegistry";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"]
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"]
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app"
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="ru" className={`${geistSans.variable} ${geistMono.variable}`}>
//       <body>
//         <AppRouterCacheProvider>
//           <ThemeRegistry>{children}</ThemeRegistry>
//         </AppRouterCacheProvider>
//       </body>
//     </html>
//   );
// }

import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";	// ← Для Next.js 16 пока используем v15
import { cookies } from "next/headers";

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const mode = cookieStore.get("theme-mode")?.value || "light";

  return (
    <html lang="ru">
      <body>
      	<AppRouterCacheProvider>
      		
        <ThemeRegistry initialMode={mode}>
          {children}
        </ThemeRegistry>
      	</AppRouterCacheProvider>
      </body>
    </html>
  );
}